CREATE TABLE SQL_NOTE (
    ID INTEGER NOT NULL IDENTITY,
    TITLE VARCHAR(128) NOT NULL,
    SQL_TEMPLATE LONGVARCHAR
);

CREATE TABLE SQL_PARAMETERS (
    SQL_ID INTEGER NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    DATA_TYPE VARCHAR(16) NOT NULL,
    SORT_ORDER INTEGER NOT NULL,
    CONSTRAINT SQL_PARAMETERS_FK1
      FOREIGN KEY (SQL_ID) REFERENCES SQL_NOTE (ID)
);

INSERT INTO SQL_NOTE VALUES (1, 'サンプルSQL', 'SELECT * FROM PERSON_TABLE WHERE NAME=${名前} AND AGE=${年齢} AND CREATE_DATE<${作成日}');
INSERT INTO SQL_PARAMETERS VALUES (1, '名前', 'STRING', 1);
INSERT INTO SQL_PARAMETERS VALUES (1, '年齢', 'NUMBER', 2);
INSERT INTO SQL_PARAMETERS VALUES (1, '作成日', 'DATE', 3);

CREATE TABLE DATA_SOURCE_CONFIGURATION (
    ID INTEGER NOT NULL IDENTITY,
    NAME VARCHAR(256) NOT NULL,
    DRIVER VARCHAR(2048) NOT NULL,
    URL VARCHAR(2048) NOT NULL,
    USER_NAME VARCHAR(2048),
    PASSWORD VARCHAR(2048)
);

INSERT INTO DATA_SOURCE_CONFIGURATION VALUES (1, 'Local MySQL', 'com.mysql.jdbc.Driver', 'jdbc:mysql://localhost/test', 'test', 'test');

--  CREATE TABLE CATEGORY_NODE (
--      ID INTEGER NOT NULL IDENTITY,
--      TITLE VARCHAR(128) NOT NULL
--  );
--  
--  CREATE TABLE TREE_STRUCTURE (
--      ID INTEGER NOT NULL IDENTITY,
--      PARENT_NODE_ID INTEGER,
--      IS_CATEGORY BOOLEAN NOT NULL,
--      CATEGORY_ID INTEGER,
--      SQL_ID INTEGER,
--      CONSTRAINT TREE_STRUCTURE_FK1
--        FOREIGN KEY (PARENT_NODE_ID)
--        REFERENCES TREE_STRUCTURE (ID),
--        
--      CONSTRAINT TREE_STRUCTURE_FK2
--        FOREIGN KEY (CATEGORY_ID)
--        REFERENCES CATEGORY_NODE (ID),
--        
--      CONSTRAINT TREE_STRUCTURE_FK3
--        FOREIGN KEY (SQL_ID)
--        REFERENCES SQL_NOTE (ID)
--  );
